contribution_alg is not set, assessor is None
client_indexes = [0, 1]
Uncaught exception
Traceback (most recent call last):
  File "/home/paul/work/FedML_tests/FMLYoloDrone/main_fedml_object_detection.py", line 14, in <module>
    model, dataset, trainer, args = init_yolo(args=args, device=device)
  File "/home/paul/work/FedML_tests/FMLYoloDrone/model/init_yolo.py", line 193, in init_yolo
    dataset = load_partition_data_coco(args, hyp, model)
  File "/home/paul/work/FedML_tests/FMLYoloDrone/data/data_loader.py", line 844, in load_partition_data_coco
    net_dataidx_map = partition_data(
  File "/home/paul/work/FedML_tests/FMLYoloDrone/data/data_loader.py", line 757, in partition_data
    n_data = len(os.listdir(data_path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/paul/fedcv_data/coco128/images/train2017/'
Uncaught exception
Traceback (most recent call last):
  File "/home/paul/work/FedML_tests/FMLYoloDrone/main_fedml_object_detection.py", line 14, in <module>
    model, dataset, trainer, args = init_yolo(args=args, device=device)
  File "/home/paul/work/FedML_tests/FMLYoloDrone/model/init_yolo.py", line 193, in init_yolo
    dataset = load_partition_data_coco(args, hyp, model)
  File "/home/paul/work/FedML_tests/FMLYoloDrone/data/data_loader.py", line 844, in load_partition_data_coco
    net_dataidx_map = partition_data(
  File "/home/paul/work/FedML_tests/FMLYoloDrone/data/data_loader.py", line 757, in partition_data
    n_data = len(os.listdir(data_path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/paul/fedcv_data/coco128/images/train2017/'
Uncaught exception
Traceback (most recent call last):
  File "/home/paul/work/FedML_tests/FMLYoloDrone/main_fedml_object_detection.py", line 14, in <module>
    model, dataset, trainer, args = init_yolo(args=args, device=device)
  File "/home/paul/work/FedML_tests/FMLYoloDrone/model/init_yolo.py", line 193, in init_yolo
    dataset = load_partition_data_coco(args, hyp, model)
  File "/home/paul/work/FedML_tests/FMLYoloDrone/data/data_loader.py", line 844, in load_partition_data_coco
    net_dataidx_map = partition_data(
  File "/home/paul/work/FedML_tests/FMLYoloDrone/data/data_loader.py", line 757, in partition_data
    n_data = len(os.listdir(data_path))
FileNotFoundError: [Errno 2] No such file or directory: '/home/paul/fedcv_data/coco128/images/train2017/'
